export const targetAudienceOptions = [
  { name: 'Teens', category: 'Age' },
  { name: 'Young adults', category: 'Age' },
  { name: 'Adults', category: 'Age' },
  { name: 'Middle-aged adults', category: 'Age' },
  { name: 'Seniors', category: 'Age' },
  { name: 'Male', category: 'Gender' },
  { name: 'Female', category: 'Gender' },
  { name: 'Non-binary', category: 'Gender' },
  {
    name: 'Fitness and wellness',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Food and cooking',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Travel and adventure',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Fashion and beauty',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Technology and gaming',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Music and entertainment',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Art and culture',
    category: 'Interests/Hobbies',
  },
  {
    name: 'Business and entrepreneurship',
    category: 'Professional Fields',
  },
  { name: 'Education and academia', category: 'Professional Fields' },
  {
    name: 'Healthcare and wellness',
    category: 'Professional Fields',
  },
  {
    name: 'Creative arts and design',
    category: 'Professional Fields',
  },
  { name: 'Science and technology', category: 'Professional Fields' },
  { name: 'Sports and athletics', category: 'Professional Fields' },
  { name: 'Students', category: 'Demographics' },
  { name: 'Working professionals', category: 'Demographics' },
  { name: 'Parents and caregivers', category: 'Demographics' },
  { name: 'National audience', category: 'Geographic Location' },
  { name: 'International audience', category: 'Geographic Location' },
  { name: 'English speakers', category: 'Language' },
  { name: 'Non-English speakers', category: 'Language' },
  { name: 'LGBTQ+ community', category: 'Niche Communities' },
  { name: 'Environmental activists', category: 'Niche Communities' },
  { name: 'Pet lovers', category: 'Niche Communities' },
  { name: 'Bookworms', category: 'Niche Communities' },
  { name: 'Gamers', category: 'Niche Communities' },
  { name: 'All', category: 'All' },
];
